# Deploy only Ecom.Api to Azure App Service
name: Build and deploy Ecom.Api to Azure Web App - Ecommerce-Shop

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Ecom.Api/Ecom.Api.csproj

      - name: Build
        run: dotnet build ./Ecom.Api/Ecom.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Ecom.Api/Ecom.Api.csproj --configuration Release --no-build -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Ecommerce-Shop'     # 👈 thay bằng đúng tên App Service của bạn
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./publish
